export const movies = [
    {
        img: "movies/movie-1.webp",
        title: "Star Wars: Episode VII The Force Awakens",
        status: "New",
        year: "2015",
        length: "2h 30m",
        resolution: "4K",
        rating: "10+",
        description: "Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.",
        cast: "Daisy Ridley, Adam Driver, Harrison Ford, John Boyega",
        genres: "Action, Drama, Sci-Fi",
        type: "positive",
        movie_category: "trending",
    },
    {
        img: "movies/movie-2.webp",
        title: "Shawshank Redemption",
        status: "Classic",
        year: "1994",
        length: "2h 22m",
        resolution: "1080p",
        rating: "16+",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        cast: "Tim Robbins, Morgan Freeman, Bob Gunton",
        genres: "Drama",
        type: "awesome",
        movie_category: "trending",
    },
    {
        img: "movies/movie-3.webp",
        title: "Rio",
        status: "Popular",
        year: "2011",
        length: "1h 36m",
        resolution: "720p",
        rating: "6+",
        description: "When Blu, a domesticated macaw from small-town Minnesota, meets the fiercely independent Jewel, he takes off on an adventure to Rio de Janeiro with the bird of his dreams.",
        cast: "Jesse Eisenberg, Anne Hathaway, George Lopez",
        genres: "Animation, Adventure, Comedy",
        type: "badoodles",
        movie_category: "trending",
    },
    {
        img: "movies/movie-4.jpg",
        title: "Frozen",
        status: "Trending",
        year: "2013",
        length: "1h 42m",
        resolution: "1080p",
        rating: "6+",
        description: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        cast: "Kristen Bell, Idina Menzel, Jonathan Groff",
        genres: "Animation, Adventure, Comedy",
        type: "sabog",
        movie_category: "trending",
    },
    {
        img: "movies/movie-5.webp",
        title: "Triple Frontier",
        status: "New",
        year: "2019",
        length: "2h 5m",
        resolution: "4K",
        rating: "16+",
        description: "Loyalties are tested when five friends reunite to take down a South American drug lord, unleashing a chain of unintended consequences.",
        cast: "Ben Affleck, Oscar Isaac, Charlie Hunnam",
        genres: "Action, Adventure, Crime",
        type: "positive",
        movie_category: "trending",
    },
    {
        img: "movies/movie-6.jpg",
        title: "Star Wars: Episode II Attack of the Clones",
        status: "Classic",
        year: "2002",
        length: "2h 22m",
        resolution: "1080p",
        rating: "10+",
        description: "Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the senator and discovers a secret clone army crafted for the Jedi.",
        cast: "Hayden Christensen, Natalie Portman, Ewan McGregor",
        genres: "Action, Adventure, Fantasy",
        type: "awesome",
        movie_category: "trending",
    },
    {
        img: "movies/movie-7.jpg",
        title: "Avengers: Endgame",
        status: "Popular",
        year: "2019",
        length: "3h 1m",
        resolution: "4K",
        rating: "12+",
        description: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos' actions and restore order to the universe.",
        cast: "Robert Downey Jr, Chris Evans, Scarlett Johansson",
        genres: "Action, Adventure, Sci-Fi",
        type: "badoodles",
        movie_category: "trending",
    },
    {
        img: "movies/movie-8.jpg",
        title: "Shrek 2",
        status: "Classic",
        year: "2004",
        length: "1h 33m",
        resolution: "1080p",
        rating: "6+",
        description: "Princess Fiona's parents invite her and Shrek to dinner to celebrate her marriage. If only they knew the newlyweds were both ogres.",
        cast: "Mike Myers, Eddie Murphy, Cameron Diaz",
        genres: "Animation, Adventure, Comedy",
        type: "sabog",
        movie_category: "trending",
    },
    {
        img: "movies/movie-9.jpg",
        title: "Shrek",
        status: "Old",
        year: "2001",
        length: "1h 30m",
        resolution: "1080p",
        rating: "6+",
        description: "An ogre, in order to regain his swamp, travels along with an annoying donkey in order to bring a princess to a scheming lord, wishing himself King. An ogre, in order to regain his swamp, travels along with an annoying donkey in order to bring a princess to a scheming lord, wishing himself King.",
        cast: "Mike Myers, Eddie Murphy, Cameron Diaz, John Lithgow",
        genres: "Animation, Adventure, Comedy",
        type: "positive",
        movie_category: "trending",
    },
    {
        img: "movies/movie-10.jpeg",
        title: "Shrek the Third",
        status: "Old",
        year: "2007",
        length: "1h 33m",
        resolution: "1080p",
        rating: "6+",
        description: "When his new father-in-law, King Harold falls ill, Shrek is looked at as the heir to the land of Far, Far Away. Not one to give up his beloved swamp, Shrek recruits his friends Donkey and Puss in Boots to install the rebellious Artie as the new king. Princess Fiona, however, rallies a band of royal girlfriends to fend off a coup d'etat by the jilted Prince Charming.",
        cast: "Mike Myers, Eddie Murphy, Cameron Diaz, Antonio Banderas",
        genres: "Animation, Adventure, Comedy",
        type: "positive",
        movie_category: "trending",
    },


    {
        img: "movies/movie-11.jpg",
        title: "The Good, the Bad and the Ugly",
        status: "New",
        year: "1966",
        length: "2h 58m",
        resolution: "4K",
        rating: "12+",
        description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
        cast: "Clint Eastwood, Lee Van Cleef, Eli Wallach",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-12.jpg",
        title: "Once Upon a Time in the West",
        status: "New",
        year: "1968",
        length: "2h 54m",
        resolution: "4K",
        rating: "12+",
        description: "A mysterious stranger joins a notorious outlaw and a vengeful widow in a race to find a lost fortune in this epic Western.",
        cast: "Henry Fonda, Charles Bronson, Claudia Cardinale",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-13.jpg",
        title: "Unforgiven",
        status: "New",
        year: "1992",
        length: "2h 11m",
        resolution: "4K",
        rating: "16+",
        description: "Retired gunslinger William Munny reluctantly takes one last job when he's hired to track down two cowboys who attacked a prostitute.",
        cast: "Clint Eastwood, Gene Hackman, Morgan Freeman",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-14.jpg",
        title: "Django Unchained",
        status: "New",
        year: "2012",
        length: "2h 45m",
        resolution: "4K",
        rating: "18+",
        description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        cast: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-15.jpg",
        title: "True Grit",
        status: "New",
        year: "2010",
        length: "1h 50m",
        resolution: "4K",
        rating: "14+",
        description: "A determined young girl enlists the help of a tough U.S. Marshal to track down her father's murderer in this classic Western film.",
        cast: "Hailee Steinfeld, Jeff Bridges, Matt Damon",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-16.jpg",
        title: "The Magnificent Seven",
        status: "New",
        year: "2016",
        length: "2h 12m",
        resolution: "4K",
        rating: "10+",
        description: "Seven gunmen come together to help a poor village fight against savage thieves in this modern remake of a classic Western film.",
        cast: "Denzel Washington, Chris Pratt, Ethan Hawke",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-17.jpg",
        itle: "High Noon",
        status: "New",
        year: "1952",
        length: "1h 25m",
        resolution: "4K",
        rating: "10+",
         description: "A retiring Marshal must defend his town against a vengeful criminal who has been freed from jail.",
        cast: "Gary Cooper, Grace Kelly, Thomas Mitchell",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-18.jpg",
        title: "Butch Cassidy and the Sundance Kid",
        status: "New",
        year: "1969",
        length: "1h 50m",
        resolution: "4K",
        rating: "12+",
        description: "Two Western outlaws are pursued by a relentless posse in this classic film based on the true story of the Wild Bunch.",
        cast: "Paul Newman, Robert Redford, Katharine Ross",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-19.jpg",
        title: "The Searchers",
        status: "New",
        year: "1956",
        length: "1h 59m",
        resolution: "1080p",
        rating: "10+",
        description: "An embittered Civil War veteran embarks on a mission to rescue his niece from the Comanches in this iconic Western film.",
        cast: "John Wayne, Jeffrey Hunter, Vera Miles",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },
    {
        img: "movies/movie-20.jpg",
        title: "Stagecoach",
        status: "New",
        year: "1939",
        length: "1h 36m",
        resolution: "1080p",
        rating: "10+",
        description: "A diverse group of strangers must band together to survive a dangerous stagecoach journey in this classic Western film.",
        cast: "John Wayne, Claire Trevor, Andy Devine",
        genres: "Western",
        type: "positive",
        movie_category: "western",
    },


    {
        img: "movies/movie-21.jpg",
        title: "Crouching Tiger, Hidden Dragon",
        status: "New",
        year: "2000",
        length: "2h",
        resolution: "4K",
        rating: "12+",
        description: "In 19th century Qing Dynasty China, a legendary warrior embarks on a quest to recover a stolen sword and finds love along the way.",
        cast: "Chow Yun-fat, Michelle Yeoh, Zhang Ziyi",
        genres: "Action, Adventure, Drama",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-22.jpg",
        title: "Ip Man",
        status: "New",
        year: "2008",
        length: "1h 46m",
        resolution: "4K",
        rating: "12+",
        description: "During the Japanese invasion of 1937, a martial artist is forced to defend his honor and his home against foreign aggressors.",
        cast: "Donnie Yen, Simon Yam, Lynn Hung",
        genres: "Action, Biography, Drama",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-23.jpg",
        title: "Seven Samurai",
        status: "New",
        year: "1954",
        length: "3h 27m",
        resolution: "4K",
        rating: "10+",
        description: "In this classic Japanese film, a village hires samurai to protect them from bandits, leading to an epic battle for survival.",
        cast: "Toshiro Mifune, Takashi Shimura",
        genres: "Adventure, Drama",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-24.jpg",
        title: "Oldboy",
        status: "New",
        year: "2003",
        length: "2h",
        resolution: "4K",
        rating: "18+",
        description: "After being kidnapped and imprisoned for 15 years, a man seeks revenge on his captors in this twisted South Korean thriller.",
        cast: "Choi Min-sik, Yu Ji-tae, Kang Hye-jung",
        genres: "Action, Drama, Mystery",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-25.jpg",
        title: "Infernal Affairs",
        status: "New",
        year: "2002",
        length: "1h 41m",
        resolution: "4K",
        rating: "14+",
        description: "Two moles, one police and one criminal, race to uncover each other's identity in this gripping Hong Kong crime thriller.",
        cast: "Andy Lau, Tony Leung, Anthony Wong",
        genres: "Crime, Drama, Mystery",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-26.jpg",
        title: "The Host",
        status: "New",
        year: "2006",
        length: "2h",
        resolution: "4K",
        rating: "14+",
        description: "When a monster emerges from Seoul's Han River, a dysfunctional family must band together to rescue their youngest member.",
        cast: "Song Kang-ho, Byun Hee-bong, Park Hae-il",
        genres: "Comedy, Drama, Horror",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-27.jpg",
        title: "Rashomon",
        status: "New",
        year: "1950",
        length: "1h 28m",
        resolution: "4K",
        rating: "10+",
        description: "In this iconic Japanese film, different perspectives on a murder are explored through the conflicting testimonies of witnesses.",
        cast: "Toshiro Mifune, Machiko Kyo, Masayuki Mori",
        genres: "Crime, Drama, Mystery",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-28.jpg",
        title: "Spring, Summer, Fall, Winter... and Spring",
        status: "New",
        year: "2003",
        length: "1h 43m",
        resolution: "4K",
        rating: "12+",
        description: "Set against a serene Buddhist temple, this South Korean drama follows a monk through different stages of life and enlightenment.",
        cast: "Oh Young-soo, Kim Ki-duk",
        genres: "Drama",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-29.jpg",
        title: "A City of Sadness",
        status: "New",
        year: "1989",
        length: "2h 37m",
        resolution: "1080p",
        rating: "10+",
        description: "During Taiwan's White Terror era, a family is torn apart by political turmoil in this moving drama from acclaimed director Hou Hsiao-hsien.",
        cast: "Tony Leung, Chen Sung Yau, Li Tian-lu",
        genres: "Drama, History",
        type: "positive",
        movie_category: "asian",
    },
    {
        img: "movies/movie-30.jpg",
        title: "Memories of Murder",
        status: "New",
        year: "2003",
        length: "2h 12m",
        resolution: "4K",
        rating: "16+",
        description: "True events inspire this gripping South Korean crime thriller about detectives trying to catch a serial killer in a rural town.",
        cast: "Song Kang-ho, Kim Sang-kyung, Kim Roe-ha",
        genres: "Crime, Drama, Mystery",
        type: "positive",
        movie_category: "asian",
    },
]